name: Update Quote Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *' # Runs every 20 minutes

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Generate and Replace Quote
        run: |
          node <<EOF
          const fs = require('fs').promises;

          const quotes = [
            { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
            { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
            { text: "Do not wait for leaders; do it alone, person to person.", author: "Mother Teresa" },
            { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
            { text: "The mind is everything. What you think you become.", author: "Buddha" },
            { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
            { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
            { text: "It is never too late to be what you might have been.", author: "George Eliot" },
            { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
            { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
            { text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama" },
            { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
            { text: "In three words I can sum up everything I’ve learned about life: it goes on.", author: "Robert Frost" },
            { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
            { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
            { text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller" },
            { text: "Keep your face always toward the sunshine - and shadows will fall behind you.", author: "Walt Whitman" },
            { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
            { text: "Let us not look back in anger, nor forward in fear, but around in awareness.", author: "James Thurber" },
            { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
            { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
            { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
            { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
            { text: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr." },
            { text: "If I have seen further than others, it is by standing upon the shoulders of giants.", author: "Isaac Newton" },
            { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein" },
            { text: "The important thing is not to stop questioning. Curiosity has its own reason for existence.", author: "Albert Einstein" },
            { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
            { text: "Strive for progress, not perfection.", author: "Unknown" },
            { text: "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", author: "Oprah Winfrey" },
            { text: "You don't have to control your thoughts. You just have to stop letting them control you.", author: "Dan Millman" },
            { text: "Peace begins with a smile.", author: "Mother Teresa" },
            { text: "It is not what happens to you, but how you react to it that matters.", author: "Epictetus" },
            { text: "The only constant in life is change.", author: "Heraclitus" },
            { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane" },
            { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
            { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
            { text: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", author: "Unknown" },
            { text: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs" },
            { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
            { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
          ];

          function getRandomQuote() {
            const randomIndex = Math.floor(Math.random() * quotes.length);
            return quotes[randomIndex];
          }

          async function main() {
            const newQuote = getRandomQuote();
            const quoteLine = `          document.getElementById("quote").innerText = "${newQuote.text}";`;
            const authorLine = `          document.getElementById("author").innerText = "- ${newQuote.author}";`;

            try {
              let indexHTML = await fs.readFile('./index.html', 'utf8');
              const updatedHTML = indexHTML.replace(/document\.getElementById\("quote"\)\.innerText = ".*";/, quoteLine)
                                            .replace(/document\.getElementById\("author"\)\.innerText = "- .*";/, authorLine);

              await fs.writeFile('./index.html', updatedHTML, 'utf8');
            } catch (error) {
              console.error("Error reading or writing index.html:", error);
            }
          }

          main().catch(err => console.error("Unhandled error:", err));
          EOF

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update quote"
          push_options: '--force' # Be cautious with --force, consider removing if not needed
